countries:
  cron: "0 * * * *"
  class: "CountriesWorker"
  queue: default

states:
  cron: "0 * * * *"
  class: "StatesWorker"
  queue: default

florida:
  cron: "0 * * * *"
  class: "FloridaWorker"
  queue: default